def presentacion():
    print("**********************************************************************************")
    print("*                                                                                *")
    print("*                 B  I  E    N   V   E   N   I   D   O   S                       *")
    print("*                                                                                *")
    print("*               P R O Y E C T O    I N T E G R A D O R    N - 1                  *")
    print("*                                                                                *")
    print("*               A U L A      N - 13      G R U P O        N - 5                  *")
    print("*                                                                                *")
    print("**********************************************************************************")
    print("**********************************************************************************")
    print("*                                                                                *")
    print("*    C O L A B O R A D O R E S :                                                 *")
    print("*                                                                                *")
    print("*    Seminario, Andrea                                                           *")
    print("*    Senese, Daiana                                                              *")
    print("*    Sorbera Florencia                                                           *")
    print("*    Torres, Joaquin                                                             *")
    print("*                                                                                *")
    print("**********************************************************************************")
